# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in collatz.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rdoc", "~> 6.5"

gem "rspec", "~> 3.12"

gem "rubocop", "~> 1.44"
