# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in collatz.gemspec
gemspec

gem "rake", "~> 13.1"

gem "rdoc", "~> 6.6"

gem "rspec", "~> 3.13"

gem "rubocop", "~> 1.62"
