version: 2
# Any missing ecosystem willn't be accepted / added.
# https://github.com/dependabot/dependabot-core/issues/3943
updates:
# Workflow files stored in the default location of `.github/workflows`
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: "/C#"
  schedule:
    interval: monthly
# Gleam has no supported ecosystem _itself_ but might be alerted via a mix/hex
# setup, as mix for elixir is supported, and gleam uses the same hex pkg host.
- package-ecosystem: gomod
  directory: "/go"
  schedule:
    interval: weekly
- package-ecosystem: maven
  directory: "/java"
  schedule:
    interval: weekly
- package-ecosystem: npm
  directory: "/javascript"
  schedule:
    interval: weekly
  ignore:
    # https://github.com/iamturns/eslint-config-airbnb-typescript has been archived so we can't updated the eslint plugin it depends on so we can't update eslint
    - dependency-name: "eslint"
    - dependency-name: "eslint-config-*"
    - dependency-name: "eslint-plugin-*"
    - dependency-name: "@typescript-eslint/*"
  groups:
    mocha-chai:
      patterns:
      - "mocha"
      - "chai"
      - "@types/mocha"
      - "@types/chai"
# Julia has no supported ecosystem
# https://github.com/dependabot/dependabot-core/issues/2105
- package-ecosystem: pip
  directory: "/python"
  schedule:
    interval: weekly
  ignore:
  # until we drop py 3.8
  - dependency-name: "alabaster"
  # https://github.com/sphinx-doc/sphinx/pull/11511 -- until we drop py 3.8
  - dependency-name: "sphinx"
    versions: [">=7.2"]
  - dependency-name: "sphinx-*"
  - dependency-name: "sphinxcontrib-*"
  groups:
    flake8:
      patterns:
      - "flake8"
      - "pyflakes"
      - "pycodestyle"
    sphinx:
      patterns:
      - "sphinx*"
      - "furo"
      - "myst-parser"
    everything-else:
      patterns:
      - "*"
      exclude-patterns:
      - "flake8"
      - "pyflakes"
      - "pycodestyle"
      - "sphinx*"
      - "furo"
      - "myst-parser"
# R has no supported ecosystem
# https://github.com/dependabot/dependabot-core/issues/2042
- package-ecosystem: bundler
  directory: "/ruby"
  schedule:
    interval: weekly
- package-ecosystem: cargo
  directory: "/rust"
  schedule:
    interval: monthly
