# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Collatz
email: nathan.a.z.levett@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Provides the basic functionality to interact with the Collatz conjecture.
  The parameterisation uses the same (P,a,b) notation as Conway's generalisations.
  Besides the function and reverse function, there is also functionality to retrieve
  the hailstone sequence, the "stopping time"/"total stopping time", or tree-graph.
  The only restriction placed on parameters is that both P and a can't be 0.
baseurl: "/Collatz" # the subpath of your site, e.g. /blog
url: "https://skenvy.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: LevettNathan
github_username:  skenvy

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
- .sass-cache/
- .jekyll-cache/
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- README.md

include:
- python/_modules/collatz
- python/_modules/collatz/parameterised
- python/_modules/collatz/parameterised/index.html
- python/_modules/index.html
- python/_sources/collatz.parameterised.rst.txt
- python/_sources/collatz.rst.txt
- python/_sources/index.rst.txt
- python/_sources/modules.rst.txt
- python/_static/basic.css
- python/_static/debug.css
- python/_static/doctools.js
- python/_static/documentation_options.js
- python/_static/file.png
- python/_static/language_data.js
- python/_static/minus.png
- python/_static/plus.png
- python/_static/pygments.css
- python/_static/scripts
- python/_static/scripts/furo-extensions.js
- python/_static/scripts/furo.js
- python/_static/scripts/furo.js.LICENSE.txt
- python/_static/scripts/furo.js.map
- python/_static/searchtools.js
- python/_static/skeleton.css
- python/_static/sphinx_highlight.js
- python/_static/styles
- python/_static/styles/furo-extensions.css
- python/_static/styles/furo-extensions.css.map
- python/_static/styles/furo.css
- python/_static/styles/furo.css.map
- python/.doctrees/collatz.doctree
- python/.doctrees/collatz.parameterised.doctree
- python/.doctrees/environment.pickle
- python/.doctrees/index.doctree
- python/.doctrees/modules.doctree
