name: Bug Report
description: Report a bug discovered in any implementation and any version
labels: bug
body:
- type: dropdown
  id: language
  attributes:
    label: Implementation Language
    description: Which Language's Implementation was the bug found in?
    options:
      - C#
      - Go
      - Java
      - Julia
      - Node.js
      - Python
      - R
      - Ruby
      - Rust
  validations:
    required: true
- type: dropdown
  id: os
  attributes:
    label: Operating System
    description: Which Operating System was the bug on?
    options:
      - Windows
      - Linux
      - MacOS
  validations:
    required: true
- type: textarea
  id: version_of_this
  attributes:
    label: What version of Collatz did the issue happen on (either the tag, commit hash, or semver)?
  validations:
    required: true
- type: textarea
  id: version_of_lang
  attributes:
    label: What semver version of the language's runtime did the issue happen on?
  validations:
    required: true
- type: textarea
  id: repro_steps
  attributes:
    label: What were you doing (steps to reproduce the bug)?
  validations:
    required: true
- type: textarea
  id: actual_result
  attributes:
    label: What actually happened as a result?
  validations:
    required: true
- type: textarea
  id: expected_result
  attributes:
    label: What did you expect to happen?
  validations:
    required: true
- type: textarea
  id: stacktrace
  attributes:
    label: If you have a stack trace, please add it here.
- type: textarea
  id: additional
  attributes:
    label: Anything else you feel useful to add?
