name: Security Vulnerability
description: Provide details about a security vulnerability.
labels: security
body:
- type: dropdown
  id: where
  attributes:
    label: Implementation Language
    description: Which Language's Implementation does the vulnerability exist in?
    options:
      - OTHER
      - GitHub Actions
      - C#
      - Go
      - Java
      - Julia
      - Node.js
      - Python
      - R
      - Ruby
  validations:
    required: true
- type: textarea
  id: what
  attributes:
    label: What vulnerability have you discovered? Include any relevant details like a CVE.
  validations:
    required: true
- type: textarea
  id: why
  attributes:
    label: What remediation steps are known, if any.
