[package]
name = "collatz"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# Or targets: https://doc.rust-lang.org/cargo/reference/cargo-targets.html#configuring-a-target

[dependencies]
ferris-says = "0.3.1"
