# Makefile Examples Here:
# https://github.com/redis-rs/redis-rs/blob/main/Makefile
# https://gist.github.com/jlgerber/0f280236c2ee1b741dfe41a38d39a467
# https://github.com/KokaKiwi/rust-mk/blob/master/rust.mk