name = "Collatz"
uuid = "93a6299e-2ed6-4a7f-9f14-000d52f8d402"
authors = ["Skenvy <nathan.a.z.levett@gmail.com>"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
julia = "1.2.0"
