name: JavaScript 🟨🟦🟩🟥 Tests 🦂
on:
  push:
    branches-ignore:
    - 'main'
    paths:
    - 'javascript/**'
    - '!javascript/**.md'
    - '!javascript/.vscode/**'
    - '.github/workflows/javascript-*'
  pull_request:
    branches:
    - 'main'
    paths:
    - 'javascript/**'
    - '!javascript/**.md'
    - '!javascript/.vscode/**'
    - '.github/workflows/javascript-*'
  schedule: # 9AM on the 15th
  - cron: 0 22 14 1,2,3,10,11,12 * # AEDT Months
  - cron: 0 23 14 4,5,6,7,8,9 *    # AEST Months
  workflow_call:
permissions: {}
defaults:
  run:
    shell: bash
    working-directory: javascript
jobs:
  quick-test:
    name: JavaScript 🟨🟦🟩🟥 Quick Test 🦂
    if: ${{ github.event_name == 'push' && !(github.event.ref == 'refs/heads/main') }}
    runs-on: ubuntu-latest
    steps:
    - name: 🏁 Checkout
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    # Although the full test strips the nvm wrap, this setup node is purely
    # performative ~ the `make setup` without the `_=""` with run via nvm.
    - name: 🟨🟦🟩🟥 Set up Node
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version-file: 'javascript/.nvmrc'
        cache: 'npm'
        cache-dependency-path: javascript/package-lock.json
    - name: 🧱 Install build dependencies
      run: make setup
    - name: 🦂 Test
      run: make test
    - name: 🧹 Lint
      run: make lint
    - name: ⚖ Does the checked in JS match the transpiled TS? 
      run: make verify_transpiled_checkin
    - name: ⭐ JSR dry-run
      run: npm run publish:jsr:dry
  full-test:
    name: JavaScript 🟨🟦🟩🟥 Full Test 🦂
    if: >-
      ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'push' && github.event.ref == 'refs/heads/main') }}
    runs-on: '${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        # Try to track https://nodejs.org/en/about/previous-releases
        version: ['20', '22', '23'] # See package.json's "engines"
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - name: 🏁 Checkout
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - name: 🟨🟦🟩🟥 Set up Node ${{ matrix.version }}
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: '${{ matrix.version }}'
        cache: 'npm'
        cache-dependency-path: javascript/package-lock.json
    # Strip the nvm wrapping for the "full test" (it's still required by the necessary "quick test")
    - name: 🧱 Install build dependencies
      run: make setup _='' INSTALL_NODE=''
    - name: 🦂 Test
      run: make test _=''
    - name: 🧹 Lint
      run: make lint _=''
    # We probably don't need to do this on all runners, and the windows CRLF echos are annoying
    # - name: ⚖ Does the checked in JS match the transpiled TS? 
    #   run: make verify_transpiled_checkin
  built-example:
    name: JavaScript 🟨🟦🟩🟥 Build Example 🦛
    if: >-
      ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'push' && github.event.ref == 'refs/heads/main') }}
    runs-on: ubuntu-latest
    steps:
    - name: 🏁 Checkout
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - name: 🟨🟦🟩🟥 Set up Node
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version-file: 'javascript/.nvmrc'
        cache: 'npm'
        cache-dependency-path: javascript/package-lock.json
    - name: 🧱 Install build dependencies
      run: make setup
    - name: 🧱 Build
      run: make build
    - name: 🆙 Upload dists
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: Package
        path: javascript/skenvy-collatz-*.tgz
        if-no-files-found: error
        retention-days: 1
  usage-demonstration:
    name: JavaScript 🟨🟦🟩🟥 Usage Demonstration 🦏
    needs: [built-example]
    if: >-
      ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'push' && github.event.ref == 'refs/heads/main') }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: javascript/.demo
    steps:
    - name: 🏁 Checkout
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - name: 🟨🟦🟩🟥 Set up Node
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version-file: 'javascript/.nvmrc'
    - name: 🆒 Download dists
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: Package
        path: javascript/.demo
    - name: 🦛 Install this package
      run: npm run setup
    - name: 🦏 Transpile and run demonstration; 🦑 CJS
      run: npm run everything:cjs
    - name: 🦏 Transpile and run demonstration; 🐙 ESM
      run: npm run everything:esm
  codeql:
    name: JavaScript 🟨🟦🟩🟥 CodeQL 🛡👨‍💻🛡
    if: >- 
      ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'push' && github.event.ref == 'refs/heads/main') }}
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/github-codeql.yaml
    with:
      language: 'javascript'
  docs:
    name: JavaScript 🟨🟦🟩🟥 Docs 📄 Quick Test 🦂
    runs-on: ubuntu-latest
    steps:
    - name: 🏁 Checkout
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - name: 🟨🟦🟩🟥 Set up Node
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version-file: 'javascript/.nvmrc'
        cache: 'npm'
        cache-dependency-path: javascript/package-lock.json
    - name: 🧱 Install build dependencies
      run: make setup
    - name: 📄 Docs
      run: make docs
