name: LaTeX 🟢🎶🐦 Tests 🦂
on:
  push:
    branches-ignore:
    - 'main'
    paths:
    - 'LaTeX/**'
    - '!LaTeX/**.md'
    - '!LaTeX/.vscode/**'
    - '.github/workflows/LaTeX-*'
  pull_request:
    branches:
    - 'main'
    paths:
    - 'LaTeX/**'
    - '!LaTeX/**.md'
    - '!LaTeX/.vscode/**'
    - '.github/workflows/LaTeX-*'
  schedule: # 9AM on the 15th
  - cron: 0 22 14 1,2,3,10,11,12 * # AEDT Months
  - cron: 0 23 14 4,5,6,7,8,9 *    # AEST Months
  workflow_call:
permissions: {}
defaults:
  run:
    shell: bash
    working-directory: LaTeX
jobs:
  pdf:
    name: LaTeX 🟢🎶🐦 PDF 📄 Quick Test 🦂
    runs-on: ubuntu-latest
    steps:
    - name: 🏁 Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: 📄 Docs
      uses: ./LaTeX/container
      with:
        make: pdf
        subdirectory: LaTeX
    - name: 🆙 Upload pdf
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: pdf
        path: LaTeX/document.pdf
        if-no-files-found: error
