name: Test payload
on:
  push:
defaults:
  run:
    shell: bash
jobs:
  dump-payload:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
