name: Check workflow_call inputs availability
on:
  push:
  workflow_call:
    inputs:
      some-input:
        description: 'An input with a default value to see if a push can read this input'
        default: 'john-doe'
        required: false
        type: string
defaults:
  run:
    shell: bash
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{ inputs.some-input }}"
